# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RSSFeedNewsParser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftSoup'

  target 'RSSFeedNewsParserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RSSFeedNewsParserUITests' do
    # Pods for testing
  end

end
